include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NeonKit

NeonKit_FILES = mobile_frickery.m NeonImage.x NeonCacheManager.m Assets.xm LegacyFixup.x StatusBar11Later.xm MasksWorkaround.x
NeonKit_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
