#!/bin/sh

rm -rf /var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/Library/Caches/com.apple.IconsCache > /dev/null 2>&1
rm -rf /var/mobile/Library/Caches/MappedImageCache/Persistent > /dev/null 2>&1
killall -9 lsd lsdiconservice iconservicesagent fontservicesd > /dev/null 2>&1

exit 0