include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NeonSettings

NeonSettings_FILES = Tweak.x
NeonSettings_CFLAGS = -fobjc-arc
NeonSettings_FRAMEWORKS = UIKit
NeonSettings_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tweak.mk
